# Chapter 1 Exercises

1. Write a code to compute the average value in torch_tensor3d

In [2]:
import torch
import numpy as np

In [26]:
# create the tensor
torch_tensor3d = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [19, 20, 21],
        [22, 23, 24]
    ]], dtype=torch.float32)

In [27]:
torch_tensor3d.shape

torch.Size([4, 2, 3])

In [43]:
print(torch.mean(torch_tensor3d, dim=0))
print(torch.mean(torch_tensor3d, dim=1))
print(torch.mean(torch_tensor3d, dim=2))
print(torch.mean(torch_tensor3d))

tensor([[10., 11., 12.],
        [13., 14., 15.]])
tensor([[ 2.5000,  3.5000,  4.5000],
        [ 8.5000,  9.5000, 10.5000],
        [14.5000, 15.5000, 16.5000],
        [20.5000, 21.5000, 22.5000]])
tensor([[ 2.,  5.],
        [ 8., 11.],
        [14., 17.],
        [20., 23.]])
tensor(12.5000)


2. Write a code that indexes into torch_tensor3d and prints out the valu 13

In [47]:
torch_tensor3d[2,0,0]

tensor(13.)

4. Write a code that finds the solution to $f(x) = sin(x-2) * (x+2) + \sqrt{|cos(x)|}$

In [67]:
# function
def f(x):
    return torch.sin(x-2)*torch.pow((x+2),2) + torch.sqrt(torch.abs(torch.cos(x)))

In [79]:
# compute
import torch.nn as nn

learning_rate = 0.05

# Create a object for paramters
x_param = torch.nn.Parameter(torch.tensor([5.0]), requires_grad=True)
#Optimizer
optimizer = torch.optim.SGD([x_param], lr=learning_rate)

# Create the backpropagation code
for epoch in range(1000):
    optimizer.zero_grad()
    loss_incurred = f(x_param)
    loss_incurred.backward()
    optimizer.step()
print(f'x: {x_param.data}')
print(f'f(x): {f(x_param.data)}')


x: tensor([1.0635])
f(x): tensor([-6.8625])
